name: CI

on:
  push:
    branches:
      - main
      - dev

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE: ${{ github.event.repository.name }}-${{ fromJSON('{"main":"prod"}')[github.ref_name] || github.ref_name }}

jobs:

  setup:
    runs-on: ubuntu-latest
    environment: ${${{ fromJSON('{"main":"prod"}')[github.ref_name] || github.ref_name }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: ls
        run: ls -A $GITHUB_WORKSPACE
      - name: envsubst test
        run: envsubst < deploy.yaml | echo -
  
     
