name: CI

on:
  push:
    branches:
      - main
      - dev

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE: ${{ github.event.repository.name }}-${{ fromJSON('{"main":"prod"}')[github.ref_name] || github.ref_name }}

jobs:

  setup:
    runs-on: ubuntu-latest
    environment: ${{ github.event.repository.name }}-${{ fromJSON('{"main":"prod"}')[github.ref_name] || github.ref_name }}
    env:
      BUILD_TARGET: ${{ secrets.BUILD_TARGET }}
      BUILD_ARGS: API_ENDPOINT GENERATE_SOURCEMAP
    outputs: 
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - name: Print Job Description
        run: |
          echo building target \"$BUILD_TARGET\" as \"$IMAGE\" from branch \"${{ github.ref_name }}\"
      - id: matrix
        run: |
          echo '::set-output name=value::[\"a\", \"b\", \"c\"]'
      
  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    environment: ${{ github.event.repository.name }}-${{ fromJSON('{"main":"prod"}')[github.ref_name] || github.ref_name }}
    strategy:
      matrix:
        value: ${{fromJson(needs.setup.outputs.matrix)}}
    env:
      BUILD_TARGET: ${{ secrets.BUILD_TARGET }}
      BUILD_ARGS: API_ENDPOINT GENERATE_SOURCEMAP
    steps:
      - name: Test
        run: |
          echo ${{ matrix.value }}
