name: CI

on:
  push:
    branches:
      - main
      - dev

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE: ${{ github.event.repository.name }}-${{ fromJSON('{"main":"prod"}')[github.ref_name] || github.ref_name }}

jobs:

  setup:
    runs-on: ubuntu-latest
    environment: ${${{ fromJSON('{"main":"prod"}')[github.ref_name] || github.ref_name }}
    env:
      API_ENDPOINT: "${{ secrets.API_ENDPOINT }}"
      PORT: ${{ secrets.PORT }}
      REDIS_URL: ${{ secrets.REDIS_URL }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: env
        run: env | grep IMAGE
      - name: env
        run: env | grep API_ENDPOINT
      - name: envsubst test
        run: envsubst < deploy.yaml | cat -
  
     
